Add Formulary
VitorGuedesMadeira/MyPortfolio pull request #4
Opened 2022-05-31 20:05 UTC by VitorGuedesMadeira

### Formulary form section

- Added inputs
- Added textarea
- Added buttom

2022-05-31 22:06 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @VitorGuedesMadeira 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Rewquired changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 22:06 UTC, tresorsawasawa commented on style.css
>  }
- [ ] Great job so far with the design, it looks smart. So, I noticed that you didn't use the right value on the `height` property of the footer. I suggest you check the correct value from the Figma design and use it in the **.footer** class.

2022-05-31 22:06 UTC, tresorsawasawa commented on index.html
> +                </ul>
- [ ] Kindly make sure you used all correct **colors** for the **Get in Touch** button in `Enabled`, `hover`, and `Pressed` mode on the **background** and **text color** to stick to the design templates in [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) as much as possible. I suggest you check the ones used on the Figma design and apply them to this **button** styling. You can check from this image below on Figma and you will find the used colors.
![btn_colors](https://user-images.githubusercontent.com/83042742/171287444-65138717-e88a-4cee-ad08-e3f7179594b1.png)

2022-05-31 22:06 UTC, tresorsawasawa commented on index.html
> +                    <li><textarea name="message" id="message" cols="30" rows="10" placeholder="Enter text here" maxlength="500" required></textarea></li>
- [ ] I think it would be better to use the correct **colors**, **font-size**, **font-weight**, and **spacing(padding, margins)** on the form's elements(inputs and textarea) to make your project's design match the Figma template as much as possible.

2022-05-31 22:06 UTC, tresorsawasawa commented on index.html
> +
- [ **OPTIONAL** ] I think it would be better :+1: :100: if you use a `<p>` tag on these texts instead of the `<h2>` as it is a paragraph and not a title for good HTML semantics and best practices. Also, make sure you use the correct `font-weight` like the one used in the **Figma** design. I know you can do it :muscle:.

2022-05-31 22:06 UTC, tresorsawasawa commented on index.html
>          </section>
- [ ] I think it would be :+1:  better to use the correct `background color` like the one used in the **Figma** design to make your project match perfectly the `Figma` template. I suggest you check correctly the provided one and apply it to your project. I know you do it :muscle: :muscle:

2022-06-01 16:31 UTC, Ginohmk approved these changes
Hi @VitorGuedesMadeira , 

# STATUS: APPROVED 🟢

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 14:59 UTC, merged